apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-service
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - staging
      - production

  selector:
    matchLabels:
      app: user-service

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
      scheme: http